services:
  - type: web
    name: backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        value: django-insecure-1c0%moo=4#arobz3ded0^k%njil&lg5_lhp7i^7mvvbkry8)rs
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: *
