services:
  - type: web
    name: fsl-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.10
